### ISSUE TITLE
Bug found

### ISSUE THREAD

**Issue by iZeaoGamer** [JackMD/MysteryCrate#110] opened 2019-02-12 11:12 UTC
Hey, I've found a bug with the latest MysteryCrates update you released on poggit.
When opening the crates, you can get the items before the crates have been finished opening. Example: If you open the crate, you can just take things out accordingly before the crate has been finished opening. This is a major bug, and I hope this get's fixed soon. As some of my players are experiencing this problem. Thank you!

**Comment by JackMD** [comment] 2019-02-12 11:20
What do you mean by ` you can get the items before the crates have been finished opening`? Also I hardy understand the example. I neef steps and clear steps to reproduce the issue. If you are talking about receiving the item after closing the inventory menu (while the task is running i.e the items are scrolling) then a random item is selected out of config. And thats an intended behavior (not a bug). So steps to reproduce this are needed.

**Comment by iZeaoGamer** [comment] 2019-02-12 13:16
1. Open the crate.
2. Before the task has been completed (when the crate item is meant to be shown as to what you get), you can just get whatever items you want (without the task finishing). (So basically, you can get whatever items you want without it being random. Just click the item in the crate, and you can take it out even before the task has finished.

**Comment by JackMD** [comment] 2019-02-12 14:52
Make sure you have set the crate world properly in config.yml. Also make sure that none other plugins are interfering with crates. I just tested it (again) and cannot reproduce this bug. Given that the number of people using MysteryCrate and only you reporting the bug makes me to come to the conclusion that its something wrong at your end. (Also don't hesitate to report again. As this plugin would never have been this good without people reporting bugs).

**Closed by JackMD** 2019-02-12 14:52 UTC
Labels: NIF, Status: Pending, Unconfirmed
