### ISSUE TITLE
Same Meta

### ISSUE THREAD

**Issue by IonicSyz1823** [JackMD/MysteryCrate#24] opened 2018-05-12 05:28 UTC
This plugin has the same issue as PiggyCrate

https://github.com/DaPigGuy/PiggyCrates/issues/8

**Comment by IonicSyz1823** [comment] 2018-05-12 05:42
Actually it was same ID that caused it

**Comment by JackMD** [comment] 2018-05-12 05:46
I actually will test it before pushing updates..

**Comment by JackMD** [comment] 2018-05-12 06:01
Okay this is confirmed now

**Comment by IonicSyz1823** [comment] 2018-05-12 06:58
when will it be fix?

**Comment by JackMD** [comment] 2018-05-12 07:02
I am working on a fix. I think I know what the problem is. Just need to do further testing. Then I will push updates to GitHub. This update would be a big update considering mostly everything has been rewritten. Also now you can set more than one crates with seperate items. Kind of like PiggyCrates

**Comment by IonicSyz1823** [comment] 2018-05-12 07:39
Alright thank you, but will the fix take longer than a week?

**Comment by JackMD** [comment] 2018-05-12 08:01
I am working for the fix. Once done I will push the updates to GitHub. Hopefully today

**Comment by JackMD** [comment] 2018-05-12 09:51
okay I have found the fix. and tested it too. will be updating shortly

**Comment by JackMD** [comment] 2018-05-12 10:50
Fixed in [d47eaaa](https://github.com/JackMD/MysteryCrate/commit/d47eaaa4f6650faa805d9c957e13ce751f93a83d)

**Closed by JackMD** 2018-05-12 10:50 UTC
Labels: Status: Confirmed, bug
