### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by ManiakMCPE** [JackMD/MysteryCrate#63] opened 2018-06-16 08:04 UTC
When a player spam clicks a crate when they don't have a key to open it, it causes the server to lag really bad. Please add some sort of cooldown to prevent this.

**Comment by JackMD** [comment] 2018-06-16 09:40
But how come the lagg occurs in the first place? The event is cancelled anyway.

**Comment by ManiakMCPE** [comment] 2018-06-17 20:01
It may be because it spams the message. It mainly happens when someone uses a really high cps auto clicker on it just to lag the server.

**Comment by JackMD** [comment] 2018-06-17 21:56
Wth. How come sending messages cause lagg?

**Comment by JackMD** [comment] 2018-06-21 18:40
Closing since I cannot reproduce this issue. Plus if the player is in cooldown a message will still be sent to the player that he cannot use the crate or whatever. So its not required.

**Closed by JackMD** 2018-06-21 18:40 UTC
Labels: Cannot Reproduce
